### ISSUE TITLE
live555最大推流的路数

### ISSUE THREAD

**Issue by j201111100523** [7956968/live666#1]
刚开始了解live555，通过官方文档的一些描述，了解到live555最多支持64路推流，不知道是不是有这个限制，想请教一下，期待您的回复

**Comment by 7956968** [comment]
64路限制有出处吗？我这个原理是建立了很多个live555句柄，所以是没有限制的。实际中我测试跑到300路。更高的我这没有需求。就没测。

**Comment by 7956968** [comment]
> 刚开始了解live555，通过官方文档的一些描述，了解到live555最多支持64路推流，不知道是不是有这个限制，想请教一下，期待您的回复

64路限制有出处吗？我这个原理是建立了很多个live555句柄，所以是没有限制的。实际中我测试跑到300路。更高的我这没有需求。就没测。
